name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
    tags:

env:
  php_extensions: ctype,intl,json,libxml,mbstring
  default_php: 8.2

jobs:
  ci:
    uses: laminas/workflow-continuous-integration/.github/workflows/continuous-integration.yml@1.x

  composer-require-checker:
    name: "Check for missing dependencies"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@2.30.0
        with:
          php-version: ${{ env.default_php }}
          ini-values: memory_limit=-1
          extensions: ${{ env.php_extensions }}
      - uses: "ramsey/composer-install@3.0.0"
      - run: composer global config bin-dir /usr/local/bin
      - run: composer global require -W maglnet/composer-require-checker
      - run: /usr/local/bin/composer-require-checker check
